# Le nom de votre workflow
name: quelpoke

# Quand est-ce que ce robot doit s'activer ?
on:
  push:
    branches: [ "main" ] # Ici, il s'active dès qu'on envoie du code sur la branche 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # On utilise un ordinateur virtuel Linux fourni par GitHub

    steps:
      # Étape 1 : Copier votre code sur l'ordinateur virtuel
      - name: Checkout code
        uses: actions/checkout@v4

      # Étape 2 : Se connecter à Docker Hub (ou un autre registre)
      # Note : Il faudra configurer vos identifiants dans les "Secrets" de GitHub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.MON_SECRET }}
          password: ${{ secrets.TOKEN }}

      # Étape 3 : Construire l'image et l'envoyer (Push)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./.github/workflows
          file: Dockerfile # Où se trouve le Dockerfile (ici, à la racine)
          push: true
          tags: z7zseth/goseth:latest # Le nom de votre image
